language: objective-c
osx_image: xcode9.4
xcode_workspace: Spotify.xcworkspace

before_install:
   - gem install cocoapods
   - pod install

script: 
   - xcodebuild test -workspace Spotify.xcworkspace -scheme "Spotify" -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
